
groups: []

resources:
- name: cliaas
  type: git
  source:
    uri: git@github.com:pivotal-cf/cliaas.git
    branch: master
    private_key: {{git_private_key}}

- name: github-rc
  type: github-release
  source:
    release: false
    pre_release: true
    user: pivotal-cf
    repository: cliaas
    access_token: {{github_token}}

- name: github-release
  type: github-release
  source:
    user: pivotal-cf
    repository: cliaas
    access_token: {{github_token}}

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:pivotal-cf/cliaas.git
    branch: version
    file: version
    private_key: {{git_private_key}}

jobs:
  - name: test
    plan:
      - get: cliaas
        trigger: true
      - task: install-dependencies
        file: cliaas/ci/install-dependencies.yml
      - task: unit
        file: cliaas/ci/unit.yml
      - aggregate:
        - try:
            task: aws-integration
            file: cliaas/ci/integration.yml
            params:
              IAAS: aws
              AWS_ACCESS_KEY: {{aws_access_key}}
              AWS_SECRET_KEY: {{aws_secret_key}}
              AWS_REGION: {{aws_region}}
              AWS_VPC: {{aws_vpc}}
        - task: gcp-integration
          file: cliaas/ci/integration.yml
          params:
            IAAS: gcp
            GCP_CREDS: {{gcp_creds}}
            GCP_PROJECT: {{gcp_project}}
            GCP_ZONE: {{gcp_zone}}
        - task: azure-integration
          file: cliaas/ci/integration.yml
          params:
            IAAS: azure 
            AZURE_SUBSCRIPTION_ID: {{azure_subscription_id}} 
            AZURE_CLIENT_ID: {{azure_client_id}}
            AZURE_CLIENT_SECRET: {{azure_client_secret}}
            AZURE_TENANT_ID: {{azure_tenant_id}} 
            AZURE_RESOURCE_GROUP_NAME: {{azure_resource_group_name}} 
            AZURE_NIC_ID: {{azure_nic_id}} 
            AZURE_STORAGE_ACCOUNT_NAME: {{azure_storage_account_name}}
            AZURE_STORAGE_ACCOUNT_KEY: {{azure_storage_account_key}}
            AZURE_STORAGE_CONTAINER_NAME: {{azure_storage_container_name}}
            AZURE_STORAGE_BASE_URL: {{azure_storage_base_url}}

  - name: create-patch-rc
    serial_groups: [version]
    plan:
      - aggregate:
        - get: cliaas
          passed: [test]
        - get: version
          params: {bump: patch, pre: rc}
      - task: install-dependencies
        file: cliaas/ci/install-dependencies.yml
      - task: build
        file: cliaas/ci/build-linux.yml
      - task: create-release-notes
        file: cliaas/ci/create-release-notes.yml
      - put: github-rc
        params:
          name: release-notes/name
          tag: release-notes/tag
          globs:
          - linux-binary/*
      - put: version
        params: {bump: patch, pre: rc}

  - name: create-minor-rc
    serial_groups: [version]
    plan:
      - aggregate:
        - get: cliaas
          passed: [test]
        - get: version
          params: {bump: minor, pre: rc}
      - task: install-dependencies
        file: cliaas/ci/install-dependencies.yml
      - task: build
        file: cliaas/ci/build-linux.yml
      - task: create-release-notes
        file: cliaas/ci/create-release-notes.yml
      - put: github-rc
        params:
          name: release-notes/name
          tag: release-notes/tag
          globs:
          - linux-binary/*
      - put: version
        params: {bump: minor, pre: rc}

  - name: create-major-rc
    serial_groups: [version]
    plan:
      - aggregate:
        - get: cliaas
          passed: [test]
        - get: version
          params: {bump: major, pre: rc}
      - task: install-dependencies
        file: cliaas/ci/install-dependencies.yml
      - task: build
        file: cliaas/ci/build-linux.yml
      - task: create-release-notes
        file: cliaas/ci/create-release-notes.yml
      - put: github-rc
        params:
          name: release-notes/name
          tag: release-notes/tag
          globs:
          - linux-binary/*
      - put: version
        params: {bump: major, pre: rc}

  - name: create-final-patch-release
    serial_groups: [version]
    plan:
      - aggregate:
        - get: cliaas
          passed: [create-patch-rc]
        - get: version
          passed: [create-patch-rc]
          params: {bump: final}
      - task: install-dependencies
        file: cliaas/ci/install-dependencies.yml
      - task: build
        file: cliaas/ci/build-linux.yml
      - task: create-release-notes
        file: cliaas/ci/create-release-notes.yml
      - put: github-release
        params:
          name: release-notes/name
          tag: release-notes/tag
          globs:
          - linux-binary/*
      - put: version
        params: {bump: final}

  - name: create-final-minor-release
    serial_groups: [version]
    plan:
      - aggregate:
        - get: cliaas
          passed: [create-minor-rc]
        - get: version
          passed: [create-minor-rc]
          params: {bump: final}
      - task: install-dependencies
        file: cliaas/ci/install-dependencies.yml
      - task: build
        file: cliaas/ci/build-linux.yml
      - task: create-release-notes
        file: cliaas/ci/create-release-notes.yml
      - put: github-release
        params:
          name: release-notes/name
          tag: release-notes/tag
          globs:
          - linux-binary/*
      - put: version
        params: {bump: final}

  - name: create-final-major-release
    serial_groups: [version]
    plan:
      - aggregate:
        - get: cliaas
          passed: [create-major-rc]
        - get: version
          passed: [create-major-rc]
          params: {bump: final}
      - task: install-dependencies
        file: cliaas/ci/install-dependencies.yml
      - task: build
        file: cliaas/ci/build-linux.yml
      - task: create-release-notes
        file: cliaas/ci/create-release-notes.yml
      - put: github-release
        params:
          name: release-notes/name
          tag: release-notes/tag
          globs:
          - linux-binary/*
      - put: version
        params: {bump: final}
