
groups: []

resources:
- name: cliaas
  type: git
  source:
    uri: git@github.com:c0-ops/cliaas.git
    branch: master
    private_key: {{git-private-key}}


jobs:
  - name: test
    plan:
      - get: cliaas
        trigger: true
      - task: install-dependencies
        file: cliaas/ci/install-dependencies.yml
      - task: unit
        file: cliaas/ci/unit.yml
      - aggregate:
        - task: aws-integration
          file: cliaas/ci/integration.yml
          params:
            IAAS: aws
            AWS_ACCESS_KEY: {{aws_access_key}}
            AWS_SECRET_KEY: {{aws_secret_key}}
            AWS_REGION: {{aws_region}}
            AWS_VPC: {{aws_vpc}}
        - task: gcp-integration
          file: cliaas/ci/integration.yml
          params:
            IAAS: gcp
            GCP_CREDS: {{gcp_creds}}
            GCP_PROJECT: {{gcp_project}}
            GCP_ZONE: {{gcp_zone}}

