
groups: []

resources:
- name: cliaas
  type: git
  source:
    uri: git@github.com:c0-ops/cliaas.git
    branch: master
    private_key: {{git_private_key}}

jobs:
  - name: test
    serial_groups: [version]
    plan:
      - get: cliaas
        trigger: true
      - task: install-dependencies
        file: cliaas/ci/install-dependencies.yml
      - task: unit
        file: cliaas/ci/unit.yml
      - aggregate:
        - task: aws-integration
          file: cliaas/ci/integration.yml
          params:
            IAAS: aws
            AWS_ACCESS_KEY: {{aws_access_key}}
            AWS_SECRET_KEY: {{aws_secret_key}}
            AWS_REGION: {{aws_region}}
            AWS_VPC: {{aws_vpc}}
        - task: gcp-integration
          file: cliaas/ci/integration.yml
          params:
            IAAS: gcp
            GCP_CREDS: {{gcp_creds}}
            GCP_PROJECT: {{gcp_project}}
            GCP_ZONE: {{gcp_zone}}

  - name: create-rc
    serial_groups: [version]
    plan:
      - aggregate:
        - get: cliaas
          trigger: true
          passed: [test]
        - get: version
          params: {pre: rc}
      - task: install-dependencies
        file: cliaas/ci/install-dependencies.yml
      - task: build
        file: cliaas/ci/build-linux.yml
      - task: create-release-notes
        file: cliaas/ci/create-release-notes.yml
      - put: github-rc
        params:
          name: release-notes/name
          tag: release-notes/tag
          globs:
          - linux-binary/*
      - put: version
        params: {pre: rc}

  - name: bump-patch
    serial_groups: [version]
    plan:
    - get: version
      params: {bump: patch, pre: rc}
      passed: [create-rc]
    - put: version
      params: {file: version/version}

  - name: patch-release
    serial_groups: [version]
    plan:
      - aggregate:
        - get: cliaas
          trigger: true
          passed: [test]
        - get: version
          passed: [bump-patch]
      - task: install-dependencies
        file: cliaas/ci/install-dependencies.yml
      - task: build
        file: cliaas/ci/build-linux.yml
      - task: create-release-notes
        file: cliaas/ci/create-release-notes.yml
      - put: github-release
        params:
          name: release-notes/name
          tag: release-notes/tag
          globs:
          - linux-binary/*
      - put: version
        params: {pre: rc}

  - name: bump-minor
    serial_groups: [version]
    plan:
    - get: version
      params: {bump: minor, pre: rc}
      passed: [create-rc]
    - put: version
      params: {file: version/version}

  - name: minor-release
    serial_groups: [version]
    plan:
      - aggregate:
        - get: cliaas
          trigger: true
          passed: [test]
        - get: version
          passed: [bump-minor]
      - task: install-dependencies
        file: cliaas/ci/install-dependencies.yml
      - task: build
        file: cliaas/ci/build-linux.yml
      - task: create-release-notes
        file: cliaas/ci/create-release-notes.yml
      - put: github-release
        params:
          name: release-notes/name
          tag: release-notes/tag
          globs:
          - linux-binary/*
      - put: version
        params: {pre: rc}

  - name: bump-major
    serial_groups: [version]
    plan:
    - get: version
      params: {bump: major, pre: rc}
      passed: [create-rc]
    - put: version
      params: {file: version/version}

  - name: major-release
    serial_groups: [version]
    plan:
      - aggregate:
        - get: cliaas
          trigger: true
          passed: [test]
        - get: version
          passed: [bump-major]
      - task: install-dependencies
        file: cliaas/ci/install-dependencies.yml
      - task: build
        file: cliaas/ci/build-linux.yml
      - task: create-release-notes
        file: cliaas/ci/create-release-notes.yml
      - put: github-release
        params:
          name: release-notes/name
          tag: release-notes/tag
          globs:
          - linux-binary/*
      - put: version
        params: {pre: rc}
